# Site
repository: Kabir-Ehsan.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ehsan Kabir
title: |
 PhD Student, Computer Engineering
 University of Arkansas, Fayetteville, USA

 
email: ekabir@uark.edu
website: Kabir-Ehsan.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  Kabir-Ehsan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ekabir29
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/MyPhoto.jpg
about_content: | # this will include new lines to allow paragraphs
  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:cyan"> 
  Ehsan Kabir completed his <i>Bachelor of Science</i> in Electrical and Electronic Engineering from <i>Bangladesh University of Engineering and Technology</i> in March 2016. After graduation, he worked as a <i>Lab Instructor</i> at 
  North South University, Dhaka, Bangladesh for a year. Then he joined in Bangladesh Power Development Board as an <i>Assistant Engineer</i>, where he served for two years. He finished his <i>Master of 
  Science</i> degree in Computer Engineering from <i>University of Arkansas, Fayetteville, USA</i> in July 2023. Now he is pursuing his <i>PhD in Computer Engineering</i> at the same university and expects to
  graduate by the end of December 2025.</span> </p>

  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:yellow">Interests:</span><b> Field Programmable Gate Array, Hardware Software Co-design, Machine Learning, Data Science</b></p>

  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:yellow"> Technical Skills: </span> </p>
     - Programming languages: C, C++, VHDL, Verilog RTL, Python, Java, Microcontroller, Assembly.
     - Tools: Xilinx Vivado, Cadence, Matlab, Lumerical, Latex, Arduino, Proteus, Pspice, Quartus, Adobe Illustrator, Openscad, LabView-National Instruments, Linux OS.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <h2><nobr>University of Arkansas, Fayetteville, USA</nobr></h2>
        sub_title: <nobr>Doctor of Philosophy in Computer Engineering</nobr>
        #title: <h2><nobr>Bangladesh University of Engineering and Technology, Dhaka, Bangladesh</nobr></h2>
        #sub_title: <nobr>Bachelor of Science in Electrical and Electronic Engineering</nobr>
        #caption: August 2020 - May 2025 (Expected)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
             <p style="text-align: Right;">August 2020 - May 2025 (Expected)</p>                                                                                     
             <p style="text-align: Right;">CGPA: 4.00/4.00</p>

    <h4>Harvard University</h4><p><b>BSc Computer Science</b></p><p>2010 - 2013</p>


    #layout: list # Type of content section (list/text)
    #content:
    #  - layout: left
    #    title: <h2><nobr>University of Arkansas, Fayetteville, USA</nobr></h2>
    #    sub_title: <nobr>Master of Science in Computer Engineering</nobr>
    #    #caption: August 2020 - July 2023
    #    #quote: >
    #    #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
    #    description: | # this will include new lines to allow paragraphs
    #         <p style="text-align: Right;"> August 2020 - July 2023</p>                                                                                     
    #         <p style="text-align: Right;">CGPA: 4.00/4.00</p>           

    #content:
    #  - layout: left
    #    title: <h2><nobr>Bangladesh University of Engineering and Technology, Dhaka, Bangladesh</nobr></h2>
    #    sub_title: <nobr>Bachelor of Science in Electrical & Electronic Engineering</nobr>
    #    #caption: August 2020 - July 2023
    #    #quote: >
    #    #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
    #    description: | # this will include new lines to allow paragraphs
    #         <p style="text-align: Right;">February 2011 – March 2016</p>                                                                                     
    #         <p style="text-align: Right;">CGPA: 3.67/4.00</p>              
    
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
