# Site
repository: Kabir-Ehsan.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ehsan Kabir
title: |
 PhD Student, Computer Engineering,
 University of Arkansas, Fayetteville, USA

phone: +1-479-404-0796 
email: ekabir@uark.edu
website: Kabir-Ehsan.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  Kabir-Ehsan
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ekabir29
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/MyPhoto.jpg
about_content: | # this will include new lines to allow paragraphs
  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:cyan"> 
  Ehsan Kabir completed his <i>Bachelor of Science</i> in Electrical and Electronic Engineering from <i>Bangladesh University of Engineering and Technology</i> in March 2016. After graduation, he worked as a <i>Lab Instructor</i> at 
  North South University, Dhaka, Bangladesh for a year. Then he joined in Bangladesh Power Development Board as an <i>Assistant Engineer</i>, where he served for two years. He finished his <i>Master of 
  Science</i> degree in Computer Engineering from <i>University of Arkansas, Fayetteville, USA</i> in July 2023. Now he is pursuing his <i>PhD in Computer Engineering</i> at the same university and expects to
  graduate by the end of December 2025.</span> </p>

  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:yellow">Interests:</span><b> Field Programmable Gate Array, Hardware Software Co-design, Machine Learning, Data Science</b></p>

  <p style="font-family: Helvetica, serif; font-size:13pt;"> <span style="color:yellow"> Technical Skills: </span> </p>
     - Programming languages: C, C++, VHDL, Verilog RTL, Python, Java, Microcontroller, Assembly.
     - Tools: Xilinx Vivado, Cadence, Matlab, Lumerical, Latex, Arduino, Proteus, Pspice, Quartus, Adobe Illustrator, Openscad, LabView-National Instruments, Linux OS.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <p style="font-size:15pt;"><nobr><b>University of Arkansas, Fayetteville, USA</b></nobr></p>
               <p style="font-size:12pt;margin-bottom:20px;"><nobr>Doctor of Philosophy in Computer Engineering</nobr></p>
               <p style="font-size:15pt;"><nobr><b>University of Arkansas, Fayetteville, USA</b></nobr></p>
               <p style="font-size:12pt;margin-bottom:20px;"><nobr>Master of Science in Computer Engineering</nobr></p>            
               <p style="font-size:15pt;"><nobr><b>Bangladesh University of Engineering and Technology, Dhaka, Bangladesh</b></nobr></p>
               <p style="font-size:12pt;"><nobr>Bachelor of Science in Electrical and Electronic Engineering</nobr></p>


        #sub_title: <nobr>Doctor of Philosophy in Computer Engineering</nobr>
        #title: <h2><nobr>Bangladesh University of Engineering and Technology, Dhaka, Bangladesh</nobr></h2>
        #sub_title: <nobr>Bachelor of Science in Electrical and Electronic Engineering</nobr>
        #caption: August 2020 - May 2025 (Expected)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: |# this will include new lines to allow paragraphs
             <p style="text-align:Right;margin-bottom:-5px;">August 2020 - May 2025 (Expected)</p>                                                                                     
             <p style="text-align:Right;margin-bottom:15px;">CGPA: 4.00/4.00</p>
             <p style="text-align:Right;margin-bottom:-5px;">August 2020 - July 2023</p>                                                                                     
             <p style="text-align:Right;margin-bottom:15px;">CGPA: 4.00/4.00</p>
             <p style="text-align:Right;margin-bottom:-5px;">February 2011 - March 2016</p>                                                                                     
             <p style="text-align:Right;">CGPA: 3.67/4.00</p>

  - title: Research Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:
           <ul style="font-family:Helvetica;font-size:13pt;">
             <li style="margin-bottom:10px;"> Designed an LSTM neural network using C and RTL language for high-rate dynamic system models on FPGA. </li>
             <li style="margin-bottom:10px;"> Developed an LSTM neural network model for high-rate dynamic systems on Python.</li>
             <li style="margin-bottom:10px;"> Designed a run time programmable convolution and multilayer perceptron neural network accelerator on FPGA.</li>
             <li style="margin-bottom:10px;"> Designed a multilayer perceptron neural network accelerator for high-rate time series signal forecasting on FPGA.</li>
             <li style="margin-bottom:10px;"> Designed a surface plasmon resonance biosensor to analyze lipid molecules and detect diseases like breast cancer, anemia, and diabetes, and increased the sensitivity of the sensor.</li>
           </ul>
        
    
  - title: Engineering Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
          <ul style="font-family:Helvetica;font-size:13pt;">
             <li style="margin-bottom:10px;"> <i><b>Secured Digital System:</b></i> Designed a fault injection attack and mitigation technique for a circuit running DES algorithm on FPGA using Verilog RTL and C.</li>
             <li style="margin-bottom:10px;"> <i><b>Low Power Digital System:</b></i> Designed a multilayer perceptron neural network on FPGA using Xilinx Vivado Tools and optimized it for low power consumption, high speed, and low resource utilization using high-level synthesis. </li>
             <li style="margin-bottom:10px;"> <i><b>Recommendation System:</b></i> Used deep neural network to improve the prediction accuracy of movie ratings from Netflix Datasets using Python on the GPU.</li>
             <li style="margin-bottom:10px;"> <i><b>Handwritten Digit Classifier:</b></i> Designed machine learning models such as random forest, decision tree, multilayer perceptron, and convolution neural network for MNIST digit classification using PyTorch and ScikitLearn tools in Python. </li>
             <li style="margin-bottom:10px;"> <i><b>Smart Car Parking System:</b></i> Implemented the logic of finding the nearest vacant spot for parking from two different entrances of a parking lot using digital logic gates.</li>
             <li style="margin-bottom:10px;"> <i><b>n-Bit Cascade-able Comparator Design:</b></i> Designed a 4-bit cascade-able comparator that can also be used as an n-bit comparator after cascading in CADENCE software.</li>
             <li style="margin-bottom:10px;"> <i><b>Automated Fire Extinguisher Robot:</b></i> Built an obstacle detector robot containing a water sprayer using an Arduino Uno Board, fire sensors, light-detecting resistance, and a servo motor.</li>
           </ul>
           
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 
               <h2 style="font-size:15pt;"><nobr><i><b>Research Assistant,</b></i> University of Arkansas, Computer Engineering</nobr></h2>
               <ul style="font-family:Helvetica;font-size:13pt;">
                 <li style="margin-bottom:10px;"> <nobr>Implementing machine learning algorithms on FPGA.</nobr><br><nobr><b>Current project&#58</b> State estimation from high-rate vibration data using LSTM and Transformers on FPGA.</nobr></li>
               </ul>

               <h2 style="font-size:15pt;"><nobr><i><b>Teaching Assistant,</b></i> University of Arkansas, Computer Engineering</nobr></h2>
               <ul style="font-family:Helvetica;font-size:13pt;">
                 <li style="margin-bottom:10px;"> <nobr>Graded programming assignments of GPU Programming course.</nobr></li>
               </ul>  

               <h2 style="font-size:15pt;"><nobr><i><b>Teaching Assistant,</b></i> University of Arkansas, Physics Dept.</nobr></h2>
               <ul style="font-family:Helvetica;font-size:13pt;">
                 <li style="margin-bottom:0px;"> <nobr>Graded course papers, exams and assignments of University Physics 1 & 2 course.</nobr></li>
                 <li style="margin-bottom:10px;"> <nobr>Proctored in the lab and course exams.</nobr></li>
               </ul>      

               <h2 style="font-size:15pt;"><nobr><i><b>Assistant Engineer,</b></i> Bangladesh Power Development Board, Sunamganj, Bangladesh</nobr></h2>
               <ul style="font-family:Helvetica;font-size:13pt;">
                 <li style="margin-bottom:0px;text-align:justify;"> <nobr>Ensured uninterrupted electricity supply to 30k consumers by monitoring the operation and maintenance of 33/11kv substations, transformers, and<br> other electrical equipment.</nobr></li>
                 <li style="margin-bottom:0px;text-align:justify;"> <nobr>Supervised a team of 30 sub assistant engineers, electricians, and helpers to run the maintenance operation, solve power interruption related issues,<br> and achieve fiscal targets for minimum system loss and maximum bill collection by identifying illegal and irregular electric consumption by taking<br> necessary steps to resolve them.</nobr></li>
                 <li style="margin-bottom:10px;text-align:justify;"> <nobr>Surveyed the area under the substation for new connections and extension of the existing electrical lines to distribute power to new customers.</nobr></li>
               </ul>
               
               <h2 style="font-size:15pt;"><nobr><i><b>Lab Officer,</b></i> North South University, Dhaka, Bangladesh</nobr></h2>
               <ul style="font-family:Helvetica;font-size:13pt;">
                 <li style="margin-bottom:0px;text-align:justify;"> <nobr>Designed lab manuals to connect theoretical coursework with practical implementation on DC Circuits, Analog Electronics, Signal processing, and<br> Control System.</nobr></li>
                 <li style="margin-bottom:10px;text-align:justify;"> <nobr>Conducted lab classes, experiments, and exams for up to 40 undergraduates at a time.</nobr></li>
               </ul>                  
               
        description: | # this will include new lines to allow paragraphs
             <p style="text-align:Right;">August 2020 - May 2025 (Expected)</p><br><br><br>                                                                                     
             <p style="text-align:Right;">January 2021 – May 2021</p><br><br><br>                                                                                        
             <p style="text-align:Right;">August 2019 – June 2020</p><br><br><br>                                                                                         
             <p style="text-align:Right;">October 2017 – July 2019</p><br><br><br>    

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
